import { Inter } from "next/font/google";
import "./globals.css";
import Layout  from "./components/base_layout";
import Requisition from './modules/Requisition';
import AddNewDialog from "./modules/AddNewDialog";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
